version: "3.9"

services:
  fastfoodmanager_database:
    container_name: fastfoodmanager_database
    hostname: fastfoodmanager_database
    image: postgres:latest
    restart: "no"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fastfoodmanager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastfoodmanager"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - fastfoodmanagerDatabase:/var/lib/postgresql/data

  database_test:
    container_name: database_test
    hostname: database_test
    image: postgres:latest
    restart: "always"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: test
    ports:
      - 6500:5432

volumes:
  fastfoodmanagerDatabase:
