services:
  relaxinghippoquestsdatabase:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5435:5432
    volumes:
      - relaxinghippoquestsdatabase:/var/lib/postgresql/data

  relaxinghippoquestsserver:
    depends_on:
      relaxinghippoquestsdatabase:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgresql://dbuser:dbpassword@relaxinghippoquestsdatabase/dbname?schema=public}
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-4000}
      - POSTGRES_HOST=${POSTGRES_HOST:-relaxinghippoquestsdatabase}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - EMAIL_USER=${EMAIL_USER:-user@user.com}
      - EMAIL_PASS=${EMAIL_PASS:-password}
      - EMAIL_HOST=${EMAIL_HOST:-host}
      - EMAIL_PORT=${EMAIL_PORT:-port}
      - JWT_ACCESS_TOKEN_PRIVATE_KEY=${JWT_ACCESS_TOKEN_PRIVATE_KEY:-private}
      - JWT_ACCESS_TOKEN_PUBLIC_KEY=${JWT_ACCESS_TOKEN_PUBLIC_KEY:-public}
      - ACCESS_TOKEN_EXPIRES_IN=${ACCESS_TOKEN_EXPIRES_IN:-15}
      - FULL_CLIENT_URL=${FULL_CLIENT_URL:-url}
      - CLIENT_URL=${CLIENT_URL:-url}
      - SERVER_URL=${SERVER_URL:-url}
    image: arnaudlyard/relaxing-hippoquests-server
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/api']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - relaxinghippoquestsfiles:/app/dist/public/uploads

  relaxinghippoquestsclient:
    image: arnaudlyard/relaxing-hippoquests-client

  nginx:
    image: nginx:1.21.3
    depends_on:
      relaxinghippoquestsclient:
        condition: service_started
      relaxinghippoquestsserver:
        condition: service_healthy
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

volumes:
  relaxinghippoquestsdatabase:
  relaxinghippoquestsfiles:
